 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 workflows:
   primary:
     jobs:
       - build:
          context: Common

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: msbuild VPKSoft.Utils/VPKSoft.Utils.csproj /t:restore
       - run: msbuild VPKSoft.Utils/VPKSoft.Utils.csproj /p:Configuration=Release
       
       - run: msbuild VPKSoft.Utils.Framework/VPKSoft.Utils.Framework.csproj /t:restore
       - run: msbuild VPKSoft.Utils.Framework/VPKSoft.Utils.Framework.csproj /p:Configuration=Release
       
       - run: msbuild VPKSoft.XmlSettings/VPKSoft.XmlSettings.csproj /t:restore
       - run: msbuild VPKSoft.XmlSettings/VPKSoft.XmlSettings.csproj /p:Configuration=Release
# No need for bleeding edge       - run: dotnet tool install --global PowerShell
       - run: 
          name: Push to NuGet
          command: |
            dotnet pack VPKSoft.Utils/VPKSoft.Utils.csproj -c:Release
            ./NuGet-Push.ps1
            
